### ISSUE TITLE
[iOS] - Positioning not work

### ISSUE THREAD

**Issue by jsdussanc** [situmtech/situm-cordova-getting-started#3]
Same topic for ios in https://github.com/situmtech/situm-ios-getting-started/issues/1

The only option I have to track the user really does not work, my building is a whole block.
![imagen subida desde ios](https://user-images.githubusercontent.com/7362688/38390019-ad76dc9c-38e5-11e8-83fc-05beb03c97c5.png)
Plan of my building:
![planesteet](https://user-images.githubusercontent.com/7362688/38389997-9ef9db4c-38e5-11e8-8ac8-380dc3f5624b.png)
Calibration of my building:
![planesteet_calibracion](https://user-images.githubusercontent.com/7362688/38390006-a63eb4d6-38e5-11e8-888e-15cec0a098dd.png)
always says I'm out of the building, would I need to implement the real-time option?

**Comment by jsdussanc** [comment]
on Android work good :)

![good](https://user-images.githubusercontent.com/7362688/38390071-da877e80-38e5-11e8-8e5a-90b8263ef8d6.png)

blue Situm
green MyLocation (GoogleMaps)

**Comment by CrisBarreiro** [comment]
In case this is an issue, it should belong to the Plugin repository
